[package]
name = "Ad-fil_Blocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
hyper = "0.14.26"
tokio = "1.28.0"
tower = "0.4.13"
